### PR TITLE
#4 - Limit simultaneous training requests

### PR DESCRIPTION
**Pull request by Horsmann**
- limit training to one job at a time
- training is asynchronous now and returns immediately

### CODE REVIEW

**Comment by Horsmann** [comment]
@Rentier prediction should be asynch, too?

**Comment by jcklie** [comment]
Not for now, as we need to wait for the result on INCEpTION side anyways.

**Comment by Horsmann** [comment]
@reckart I have again the problem that the build passes on our Jenkins but the PR build on UKP's Jenkins fail?

**Comment by jcklie** [comment]
I added an error message to the assert, it just cannot find the temporary file. I do not know why. Maybe we can write it to somewhere else?

`java.lang.AssertionError: /tmp/junit3895615716130475389/classifier.ser does not exist`

**Pull request merged**
